In [82]:
## imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV,StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [40]:
### create the Dataset
X,y = make_classification(n_samples = 1000,n_features = 10, n_classes = 2,random_state = 20)

In [41]:
X

array([[-0.77228288,  0.19670614,  1.64949844, ...,  0.11495344,
         0.75403833,  1.31646629],
       [ 1.46611492, -0.56998489, -0.49092075, ..., -0.43100156,
         1.05412151, -1.37878943],
       [ 0.26515873,  2.354382  , -1.30263989, ..., -0.0789764 ,
        -0.08921751, -1.29899056],
       ...,
       [ 0.10999623,  0.15559844,  0.6135063 , ..., -0.24700341,
        -0.54999422,  0.96164937],
       [ 0.36974471,  0.89851877, -1.65166284, ...,  0.42067259,
        -0.03992643,  1.37658315],
       [ 0.3600093 ,  1.03649588, -0.24432422, ..., -0.13441277,
         0.0543356 , -1.280987  ]], shape=(1000, 10))

In [42]:
y

array([1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,

In [43]:
## train-test-split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 42)

In [44]:
## Model Training

logistic = LogisticRegression()
logistic.fit(X_train,y_train)

LogisticRegression()

In [45]:
y_pred = logistic.predict(X_test)
y_pred

array([0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0])

In [46]:
## perforance metrics
Accuracy = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print("The accuracy from the model is " ,+Accuracy)
print(cm)
print(classification_report(y_test,y_pred))

The accuracy from the model is  0.93
[[138   9]
 [ 12 141]]
              precision    recall  f1-score   support

           0       0.92      0.94      0.93       147
           1       0.94      0.92      0.93       153

    accuracy                           0.93       300
   macro avg       0.93      0.93      0.93       300
weighted avg       0.93      0.93      0.93       300



Hyperparameter Tuning and Cross Validation

In [67]:
model = LogisticRegression()
c_values = [100,10,1.0,0.1,0.01]

In [ ]:
params = [
    # Group 1: liblinear
    {'solver': ['liblinear'], 'penalty': ['l1', 'l2'], 'C': c_values},

    # Group 2: saga (supports all penalties)
    {'solver': ['saga'], 'penalty': ['l1', 'l2', 'elasticnet'], 'C': c_values, 'l1_ratio': [0.5]},

    # Group 3: others (only support l2)
    {'solver': ['lbfgs', 'newton-cg', 'sag'], 'penalty': ['l2'], 'C': c_values}
]


In [69]:
## Grid search CV
cv = StratifiedKFold()
grid = GridSearchCV(estimator = model,param_grid = params,scoring = 'accuracy',cv =cv,n_jobs = -1)
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': [100, 10, 1.0, 0.1, 0.01],
                          'penalty': ['l1', 'l2'], 'solver': ['liblinear']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'l1_ratio': [0.5],
                          'penalty': ['l1', 'l2', 'elasticnet'],
                          'solver': ['saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'penalty': ['l2'],
                          'solver': ['lbfgs', 'newton-cg', 'sag']}],
             scoring='accuracy')

In [70]:
grid.fit(X_train,y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': [100, 10, 1.0, 0.1, 0.01],
                          'penalty': ['l1', 'l2'], 'solver': ['liblinear']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'l1_ratio': [0.5],
                          'penalty': ['l1', 'l2', 'elasticnet'],
                          'solver': ['saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'penalty': ['l2'],
                          'solver': ['lbfgs', 'newton-cg', 'sag']}],
             scoring='accuracy')

In [72]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [76]:
print(grid.best_score_)


0.9542857142857143


In [79]:
y_pred = grid.predict(X_test)

In [81]:
## perforance metrics using grid search
Accuracy = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print("The accuracy from the model is " ,+Accuracy)
print(cm)
print(classification_report(y_test,y_pred))

The accuracy from the model is  0.93
[[137  10]
 [ 11 142]]
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       147
           1       0.93      0.93      0.93       153

    accuracy                           0.93       300
   macro avg       0.93      0.93      0.93       300
weighted avg       0.93      0.93      0.93       300



Randomized SearchCV

In [88]:
model = LogisticRegression()
rand = RandomizedSearchCV(estimator = model,param_distributions = params,cv = 5, scoring ='accuracy',n_jobs = -1)
rand.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions=[{'C': [100, 10, 1.0, 0.1, 0.01],
                                         'penalty': ['l1', 'l2'],
                                         'solver': ['liblinear']},
                                        {'C': [100, 10, 1.0, 0.1, 0.01],
                                         'l1_ratio': [0.5],
                                         'penalty': ['l1', 'l2', 'elasticnet'],
                                         'solver': ['saga']},
                                        {'C': [100, 10, 1.0, 0.1, 0.01],
                                         'penalty': ['l2'],
                                         'solver': ['lbfgs', 'newton-cg',
                                                    'sag']}],
                   scoring='accuracy')

In [89]:
rand.best_params_

{'solver': 'saga', 'penalty': 'elasticnet', 'l1_ratio': 0.5, 'C': 0.1}

In [92]:
rand.best_score_
print(rand.best_score_)

0.9528571428571428


In [93]:
y_pred = rand.predict(X_test)

In [94]:
## perforance metrics using randomized search
Accuracy = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print("The accuracy from the model is " ,+Accuracy)
print(cm)
print(classification_report(y_test,y_pred))

The accuracy from the model is  0.93
[[137  10]
 [ 11 142]]
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       147
           1       0.93      0.93      0.93       153

    accuracy                           0.93       300
   macro avg       0.93      0.93      0.93       300
weighted avg       0.93      0.93      0.93       300



Logistic regression for muilti class classification


In [96]:
### create the Dataset
X,y = make_classification(n_samples = 1000,n_features = 10,n_informative = 3, n_classes = 3,random_state = 42)

In [97]:
X

array([[ 0.7715326 , -1.47433614,  2.19664605, ...,  0.68174341,
         1.08996189,  0.96250289],
       [ 1.85838284, -3.68087983,  0.22749588, ..., -0.47417818,
         1.34113888, -0.77177196],
       [-0.98724764,  1.53916836,  0.5859042 , ..., -0.32202815,
        -1.45103394,  1.32543211],
       ...,
       [-1.227082  ,  1.65602784,  0.47263035, ..., -0.8634936 ,
        -1.83932326, -0.03120349],
       [ 1.28527572, -0.29715202, -0.67172079, ..., -1.31544131,
         2.85446468,  1.3094441 ],
       [-0.75428048,  0.88516075, -1.6728939 , ..., -2.0362205 ,
        -1.43989584,  0.04749347]], shape=(1000, 10))

In [98]:
y

array([1, 2, 1, 1, 2, 1, 1, 0, 2, 2, 2, 0, 1, 0, 2, 1, 2, 1, 0, 1, 1, 1,
       2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 0, 2, 0, 1, 0, 0, 2, 0, 1, 0, 2, 1,
       2, 0, 2, 0, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1, 2,
       0, 2, 2, 1, 0, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0,
       0, 1, 1, 2, 1, 0, 1, 2, 0, 2, 0, 0, 2, 1, 0, 2, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 2, 1, 2, 1, 0, 2, 0, 0, 2, 1, 0, 2, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 1, 2, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1, 2, 0, 0, 1, 0, 2, 0, 0,
       0, 1, 1, 2, 1, 2, 2, 0, 0, 0, 1, 1, 0, 2, 1, 2, 2, 2, 1, 1, 0, 2,
       1, 0, 2, 1, 2, 1, 2, 0, 1, 1, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2,
       1, 2, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0,
       2, 0, 1, 1, 2, 1, 2, 2, 2, 2, 0, 1, 0, 0, 0, 0, 2, 2, 2, 1, 1, 1,
       0, 2, 0, 0, 1, 0, 2, 0, 1, 2, 2, 2, 1, 2, 1, 0, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 0, 0, 2, 2,
       2, 1, 1, 1, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 1,

In [111]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 42)

In [112]:
logistic = LogisticRegression(multi_class = 'ovr')

In [113]:
logistic.fit(X_train,y_train)

d:\ml\python\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [114]:
y_pred = logistic.predict(X_test)

In [115]:
## perforance metrics using randomized search
Accuracy = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print("The accuracy from the model is " ,+Accuracy)
print(cm)
print(classification_report(y_test,y_pred))

The accuracy from the model is  0.68
[[79 16  8]
 [31 38 27]
 [ 3 11 87]]
              precision    recall  f1-score   support

           0       0.70      0.77      0.73       103
           1       0.58      0.40      0.47        96
           2       0.71      0.86      0.78       101

    accuracy                           0.68       300
   macro avg       0.67      0.67      0.66       300
weighted avg       0.67      0.68      0.66       300



Hyperparameter Tuning and Cross Validation for multiclass classification

In [116]:
model1 = LogisticRegression()

In [117]:
params = [
    # Group 1: liblinear
    {'solver': ['liblinear'], 'penalty': ['l1', 'l2'], 'C': c_values},

    # Group 2: saga (supports all penalties)
    {'solver': ['saga'], 'penalty': ['l1', 'l2', 'elasticnet'], 'C': c_values, 'l1_ratio': [0.5]},

    # Group 3: others (only support l2)
    {'solver': ['lbfgs', 'newton-cg', 'sag'], 'penalty': ['l2'], 'C': c_values}
]


In [120]:
## Grid search CV
cv = StratifiedKFold()
grid = GridSearchCV(estimator = model1,param_grid = params,scoring = 'accuracy',cv =cv,n_jobs = -1)
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': [100, 10, 1.0, 0.1, 0.01],
                          'penalty': ['l1', 'l2'], 'solver': ['liblinear']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'l1_ratio': [0.5],
                          'penalty': ['l1', 'l2', 'elasticnet'],
                          'solver': ['saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'penalty': ['l2'],
                          'solver': ['lbfgs', 'newton-cg', 'sag']}],
             scoring='accuracy')

In [121]:
grid.fit(X_train,y_train)

d:\ml\python\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1196: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=l1)
  warnings.warn(


GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': [100, 10, 1.0, 0.1, 0.01],
                          'penalty': ['l1', 'l2'], 'solver': ['liblinear']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'l1_ratio': [0.5],
                          'penalty': ['l1', 'l2', 'elasticnet'],
                          'solver': ['saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'penalty': ['l2'],
                          'solver': ['lbfgs', 'newton-cg', 'sag']}],
             scoring='accuracy')

In [122]:
y_pred = grid.predict(X_test)

In [123]:
grid.best_params_

{'C': 0.01, 'l1_ratio': 0.5, 'penalty': 'l1', 'solver': 'saga'}

In [124]:
grid.best_score_

np.float64(0.6528571428571428)

In [125]:
## perforance metrics using grid search
Accuracy = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print("The accuracy from the model is " ,+Accuracy)
print(cm)
print(classification_report(y_test,y_pred))

The accuracy from the model is  0.7033333333333334
[[78 17  8]
 [28 43 25]
 [ 3  8 90]]
              precision    recall  f1-score   support

           0       0.72      0.76      0.74       103
           1       0.63      0.45      0.52        96
           2       0.73      0.89      0.80       101

    accuracy                           0.70       300
   macro avg       0.69      0.70      0.69       300
weighted avg       0.69      0.70      0.69       300



In [127]:
## randomized search cv for multi class
model1= LogisticRegression()
rand = RandomizedSearchCV(estimator = model,param_distributions = params,cv = 5, scoring ='accuracy',n_jobs = -1)
rand.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions=[{'C': [100, 10, 1.0, 0.1, 0.01],
                                         'penalty': ['l1', 'l2'],
                                         'solver': ['liblinear']},
                                        {'C': [100, 10, 1.0, 0.1, 0.01],
                                         'l1_ratio': [0.5],
                                         'penalty': ['l1', 'l2', 'elasticnet'],
                                         'solver': ['saga']},
                                        {'C': [100, 10, 1.0, 0.1, 0.01],
                                         'penalty': ['l2'],
                                         'solver': ['lbfgs', 'newton-cg',
                                                    'sag']}],
                   scoring='accuracy')

In [128]:
rand.best_params_

{'solver': 'liblinear', 'penalty': 'l2', 'C': 0.01}

In [129]:
print(rand.best_score_)

0.6328571428571428


In [130]:
y_pred = rand.predict(X_test)

In [131]:
## perforance metrics using randomized search
Accuracy = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
print("The accuracy from the model is " ,+Accuracy)
print(cm)
print(classification_report(y_test,y_pred))

The accuracy from the model is  0.6666666666666666
[[83  7 13]
 [41 21 34]
 [ 2  3 96]]
              precision    recall  f1-score   support

           0       0.66      0.81      0.72       103
           1       0.68      0.22      0.33        96
           2       0.67      0.95      0.79       101

    accuracy                           0.67       300
   macro avg       0.67      0.66      0.61       300
weighted avg       0.67      0.67      0.62       300

